package uk.gov.companieshouse.taf.config;

import com.mongodb.MongoClientURI;
import java.net.UnknownHostException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.mongodb.MongoDbFactory;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.SimpleMongoDbFactory;
import org.springframework.data.mongodb.repository.config.EnableMongoRepositories;
import uk.gov.companieshouse.taf.repository.IncomingBrisMessageRepository;
import uk.gov.companieshouse.taf.repository.OutgoingBrisMessageRepository;

/**
 * This Mongo configuration is used to load data into the BRIS Test
 * outgoing_messages collection in order to submit messages through to the
 * bris_outgoing_message_consumer_test service.
 * It is also used to read messages from the BRIS Test incoming_messages collection
 * to assert that the expected messages have been processed.  Note that these
 * Mongo entries in the BRIS Test incoming_messages collection are generated by the
 * bris-incoming-message-controller-test service.
 */
@EnableMongoRepositories(basePackageClasses = {IncomingBrisMessageRepository.class,
        OutgoingBrisMessageRepository.class}, mongoTemplateRef = "templateBrisTest")
@Configuration
public class BrisTestMongoConfig extends MongoConfig {

    private static final String BRIS_MESSAGES_TEST_DATABASE = "bris_messages_test";

    @Autowired
    private Env env;

    // Mongo config for Bris Test Database for incoming and outgoing records
    @Bean
    @Qualifier("BrisTestMongoDbTemplate")
    public MongoTemplate templateBrisTest() throws UnknownHostException {
        return new MongoTemplate(mongoTestDbFactory());
    }

    @Bean
    @Qualifier("BrisTestMongoDbFactory")
    private MongoDbFactory mongoTestDbFactory() throws UnknownHostException {
        return new SimpleMongoDbFactory(new MongoClientURI(env.config.getString(MONGO_URI)
                + URI_SLASH + BRIS_MESSAGES_TEST_DATABASE));
    }
}
